# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99f8ce44e7252fe0139b0c46b8ae0b0b8bd919475030eb18ae474e4af93509817f5c991d034d9f03ff91250612ab1822190cc6f8f9bf953a973c22f0ef64ec2c

test:
  secret_key_base: 2914ddb87af788637312166e98f3164f027e53dbcc575297d370f8db90a3d6b4697c2d1e293bb4b7c4de7ee8884fdce468f103a4b22cc645837c3beea6531528

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
